### ISSUE TITLE
Should we allow user to change configuration before rerun?

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#104]
Currently, if users want to modify configuration on already finished / failed task, they have to resubmit a new task. This means all subsequent tasks that they might have already submitted need to be removed / resubmitted also. 

Instead, we could allow user to update the existing configuration on already submitted task. We should also allow user to change the branch information which is currently not even displayed on the UI (it's shown under _env.sh). 

I am not sure what kind of sideeffect we might have with updating the config from provenance point of view, however. The config for task is meant to be immutable so that datasets generated from the task can rely on the task record to find information about how the dataset is generated. If we allow user to change it, then we break that information (maybe we only allow user to change config if the task is "failed" and no dataset is generated?)

**Comment by kitchell** [comment]
Would changing this also trigger the following tasks to rerun based on the new data? I think this should only be allowed if it will automatically force all following tasks to rerun. Otherwise, like you said it will break provenance and I think that would be bad and cause confusion.

**Comment by soichih** [comment]
When a task finishes, it will automatically rerun all following tasks - even the ones that's already finished. 

Yet.. I still believe task record itself should not be modified (even if they could..) I do want user to be able to fix/update the config when they rerun the task..

If we do implement this capability, I believe the correct way to handle this is to let UI take care of submitting different tasks behind the scene while presenting a single task status UI (maybe with multiple sessions?)

**Comment by soichih** [comment]
I believe we could allow user to resubmit with modified configuration *if* the task has never successfully completed without the risk of provenance going bad. So far, no user has requested for this capability, however.
