### ISSUE TITLE
Explore use of Keycloak

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#112]
I've learned that [http://www.keycloak.org/](Keycloak) supports JWT. I should experiment and see if we can replace my authentication service with it.

**Comment by francopestilli** [comment]
Apache has a project that can do a similar thing to our in-house authentification service. perhaps we should explore whether this Apache services can replace our in-house?

**Comment by soichih** [comment]
@stevengeeky I was hoping that we can basically replace our auth service with keycloak (which supports jwt), but after a quick review it didn't seem like it would work for us.. But you could investigate this more deeply?
