### ISSUE TITLE
Application list filtering

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#122]
As we have more applications, we should start thinking about how best to organize / filter applications. I'd like to collect some ideas under this thread

Inspirations
> https://console.developers.google.com/apis/library?project=brain-life-1485532102607

**Comment by stevengeeky** [comment]
On the apps page, we could simply have a search input on the top bar (to the right of the "Brain Life" text) which would function similarly to querying with https://github.com/brain-life/cli. We could also have fields for searching by input/output datatype and then implement a function similar to queryApps()
