### ISSUE TITLE
How should user interact with published datasets

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#138]
We now have a capability to *publish* datasets by allowing users to download them to their own computers. However, we are not taking advantage of BL to allow users to re-process the dataset with same or different set of configuration parameters, or with different mix of input datasets.

For one thing, I wonder if we should encourage users to make the entire project *public* when the publish datasets from it. The list of datasets published via publication page maybe treated as "snapshot", but the real *living* data that user can actually interact with only exists under project.

We could also implement a feature where user can click on "Reprocess" button under each published dataset which will do following.
1) Create a new process, and stage all input datasets used to generate the published dataset.
2) Populate the config identical to how the dataset was generated (We currently allow app admin to change input/config.. We could store app config snapshot as part of dataset record?)
3) Allow users to modify or keep the original settings and submit it.

**Comment by soichih** [comment]
@francopestilli the content of config.json is already stored as part of data provenance, which can be used to allow user to reprocess the data with the same config used to create the published dataset.

Speaking of which, we should also implement *provenance downloader*  which converts our provenance graph into a working shell script which will download all input datasets, then submits tasks (apps) to BL or even try running it on user's own machine by git cloning all app used to generate the published dataset. This should be possible as long as all apps uses singularity / docker. 

This functionality requires users to have access to the original input datasets. 

If we could make "provenance downloader" to work, we can then use this to allow guest user to reprocess data for published datasets on their own environment.

**Comment by francopestilli** [comment]
OK lt's called provenance downloader then! That is the feature I meant!

**Comment by soichih** [comment]
We still need to polish / test `provenance.sh`, but this functionality exists for the most part. Closing this now.
