### ISSUE TITLE
Show dataset tags on the dataset selector on the dataset staging modal

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#178]
It's not showing them (anymore?)

![screenshot from 2018-06-15 21-33-09](https://user-images.githubusercontent.com/923896/41494627-c087b0fa-70e3-11e8-87fe-dc0e63254897.png)

**Comment by soichih** [comment]
Also not showing up under App Submit modal.

![screenshot from 2018-06-15 21-37-43](https://user-images.githubusercontent.com/923896/41494662-6838e7ec-70e4-11e8-8574-5dbfd0cd2696.png)

**Comment by stevengeeky** [comment]
datatype_tags was not set by the data adapter for select2. Setting it fixed the datasetselecter modal:

![dataset selecter](https://user-images.githubusercontent.com/16492624/41541772-424946c2-72e1-11e8-8b83-ae0e3263462e.png)

Also for me datatype tags seem to be showing up on the newtask modal:
![newtask](https://user-images.githubusercontent.com/16492624/41541798-4fe90ae2-72e1-11e8-9a26-176031246715.png)

I noticed something else about the dataset selecter... when I first open it up and click the datasets dropdown, it says "no results found." Results begin to appear only when I change the selected project. After changing it once, if I change it back to the original project, results are then shown.
