### ISSUE TITLE
Closing an open modal on the page it wasn't opened on returns 404 sometimes

### ISSUE THREAD

**Issue by stevengeeky** [brainlife/warehouse#186]
Steps to replicate:

1.) Go to datasets page and open the apps tab of a dataset on the dataset modal
2.) Click on an app
3.) Go back (so the modal will show), then go forward (so the modal will remain shown on the app page)
4.) Click the close button on the modal

![screen shot 2018-06-27 at 1 44 59 pm](https://user-images.githubusercontent.com/16492624/41990546-b5925a3e-7a10-11e8-964d-ddd4ef6b61ad.png)

**Comment by soichih** [comment]
Confirmed.

When the page goes out of dataset page (when the user goes forward on step 3) modal should close.
