### ISSUE TITLE
Add button to restart a pipeline rule

### ISSUE THREAD

**Issue by skoudoro** [brainlife/warehouse#204]
Hi Brain-Life Team,

It will be really useful to have a restart button near edit/trash when we want to rerun a pipeline rule. Currently, I need to trick the pipeline rule by changing the output tag. 

Thanks!

**Comment by soichih** [comment]
@skoudoro Sorry for not getting back to this sooner, but pipeline can not be rerun like you could with an imperative workflow system. If you still need a similar feature, please let me know and we can discuss it further.
