### ISSUE TITLE
Should/Could a listing of datatype(s) of a dataset be included within dataset download .tar?

### ISSUE THREAD

**Issue by yarikoptic** [brainlife/warehouse#216]
Echoing my brief question during our jitsi session, I think it might be valuable (especially for datalad crawling and aggregation of datasets) to have brainlife data types present somewhere (in a canonical location, e.g. within `.brainlife.json`)

**Comment by soichih** [comment]
OK. I've updated it to .brainlife.json. Thanks for your feedback!
