### ISSUE TITLE
Show Project cards openly without login

### ISSUE THREAD

**Issue by francopestilli** [brainlife/warehouse#226]
I would love to show the projects here:
![image](https://user-images.githubusercontent.com/2119795/57785573-05a64980-7700-11e9-800a-f1372751787b.png)

As Apps and Datatypes and Pubs, no login required.

**Comment by soichih** [comment]
Updated the project access control logic to allow non-authenticated users to browser public projects. I couldn't get *protected* projects (private projects with "list to all users" checked) to show up for non-authenticated user. This requires a bit more radical changes to our access control logic and I'd like to tread a little bit more carefully.

I've also made various updates on UI associated with this change.

**Comment by francopestilli** [comment]
@soichih this done correct?

**Comment by soichih** [comment]
I haven't exposed private projects that are "listed to all users" (aka protected project). I was going to work on it later, but if are satisfied by exposing public project, please close this ticket.
