### ISSUE TITLE
Improve application filtering on process "new process" dialog

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#46]
The current logic used to filter application under new process dialog is very basic, and it shows apps even if user doesn't have datasets with required tags. I should hide those apps.

**Comment by francopestilli** [comment]
Also, we should add "> Show More Apps" button at the bottom of the application selector to see applications that user can not currently run, but let them see which datasets/tags are needed to run those applications.

**Comment by soichih** [comment]
New process dialog no longer shows apps that has mis-matching datatype tags. 

But.. the ordering of the apps still needs improvement. At the least, I wonder if I can just sort displayed app by the number of time it has been executed by the user. 

Also, I think I should make this a modal.

**Comment by soichih** [comment]
I've been thinking about how to display the list of apps in more useful / user friendly way.

Simply sorting by number of time the app has executed would most likely results in a few app always showing up at the top regardless of what user might want to submit *next*. Apart from knowing which apps *can* be submitted next, I think it's important to take into consideration of which apps were executed previously, or more specifically, which output datasets were generated most recently. Here is the algorithm that I am thinking..

1) List output datatypes of most recently submitted apps.
2) Sort the list of all apps that can be submitted with higher sorting order with matching input datatypes and tags.
3) (optionally?) give higher priority on apps that are submitted more frequently. 

I believe this would results in user finding app that they most likely want to submit *next* toward the top of the list.
