### ISSUE TITLE
Improve filebrowser component

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#49]
The current filebrowser component has various issues.

1) It not responsive (as in screen size)
2) Files can't be sorted
3) Columns aren't aligned.
4) Overall look & feel can be improved

**Comment by soichih** [comment]
I believe I've fixed all except 3, and maybe a bit more 4 (directories can be displayed in different color?)

**Comment by soichih** [comment]
5. For text/plain files, and if the modified date is recent (maybe in the last few seconds?) auto-reload content to simulate streaming update of the log files.

**Comment by francopestilli** [comment]
It would be helpful to design the ui-tractviewer to load different data derivatives and show results either as colormap on the tracts or as a graph on the side of the tract viewer.

**Comment by soichih** [comment]
6. Update to handle symlink. And see if I can update amaretti to allow downloading of symlink as long as it's under the same workdir.

Franco, filebrowser is a compoonent that displays list of files under "Raw Output".

**Comment by soichih** [comment]
Most of the issues has been resolved.
