### ISSUE TITLE
Need a capability to let application decide the output datatype

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#84]
Currently, the output datatype and datatype_tags are statically configured as part of application registration.  We have 2 issues with this approach.

1) Some app simply *adds* new datatype tags (like app-deface). Currently, app-deface removes all existing tags and replace it with "defaced". I've thought about using "+defaced" or "-something" to add/remove tags, but then we will have a problem of deciding which input that such operations applies to, if there are more than 1 input datasets.

2) Another app like `app-tractclassification` may want to set different datatype tags based on the configuration option used (like "remove_fiber_before" or "remove_fiber_after"). So that app-LIFE_AFQ_qualitycheck can use this tag to filter out datasets that is incompatible. The simplest thing to do may be to let the input option to add a datatype_tag if a certain option is selected (and which output datatype to add it to), but it might require a bit more complex logic.

I believe the most fool proof way of dealing with this is to let the application generate products.json containing a list of outputs with desired datatype_tags so that developer can set it to whichever the tags. Brain-Life can then take this information and override the datatype_tags specified in the application registration.

Another approach, although I am not sure if it's workable, is to let application to add optional filtering of input datasets based on config used to generate the input dataset. We could even expose the full provenance of the datasets to the app so that app can decide (/validate) if it should use the input or not by examining how the dataset was created. I think such approach might be overkill.. although has the potential to even get rid of datatype_tags.

**Comment by kitchell** [comment]
i like the option 2. I think it would be useful if an app automatically tagged the output dataset based on the input configuration. So with the AFQ app it would automatically tag it "before" or "after". I could see this being useful for something like the LBspectrum app or even ensemble tracking, the output could be auto tagged with the number of eigenvalues chosen or the number of streamlines asked for.

**Comment by soichih** [comment]
When you say option 2, do you mean adding some configuration options for app registration page on Brain-Life? Or.. do you mean letting application to specify output datatype_tags by outputting it on products.json?

I kind of like the latter - although it requires a bit more work by application, because it gives developer more control over how the output datatypes is computed. This approach also allows us to implement more sophisticated validation apps; apps that read some arbitrary dwi file, analyzes it, then set appropriate datatype tags based on information that can only be found at runtime.

**Comment by kitchell** [comment]
Hm I am not sure. Using the AFQ tract classification app as an example: I was thinking if user set remove_zero_weighted_fibers to before, then the ouput dataset would automatically be tagged as "removedbefore" or something similar, and if the user set remove_zero_weighted_fibers to after then the dataset would automatically be tagged "removedafter". 

Are you asking where would be the best place to set this rule? in app registration or within the app itself? within the app itself would probably be ok.

**Comment by soichih** [comment]
> within the app itself would probably be ok
OK great.

So, to clarify this a bit further.. We will continue to let application registered with static datatype tags for each output datasets - since most app would be fine with static tags. For apps that wants to set datatype_tags dynamically, we ask application developers to generate products.json containing something like

```
[{
"id": "afq_output",
"datatype_tags": [ "removedbefore" ]
}]
```

for brain-life/app-tractclassification.

* datatype_tags within products.json will take precedence over static datatype_tags configured in application registration

*************** following is mainly a note to myself ******************

One other thing to think about.. For application that *filters* input data and creates output with the same datatype as input datatype with different datatype tags (like ACPC align, normalize, split shell, etc..) We should let them add/remove datatype_tags instead of completely resetting datatype tags. For example, if we coould let app-acpcalign to configure output datatype with something like  "+acpc_aligned" (Plus sign indicates that we are adding the tag to existing list of datatypes.), we can then run app-acpcalign on any T1 with any preexisting tags without wiping out tags that acpc_align app aren't aware of. Right now, it basically rewrites all tags with just "acpc_aligned" tag.

Problem is, though, if there are more than 1 input / outputs with the same datatype, we won't know which input dataset that we are adding / removing tags from. Looking for same datatype in input datasets would work most of the time, but very hacky. Having to specify input ID for output datatype_tags sounds confusing.

Meanwhile, we recently started passing input datasets' datatypes via config.json.  App can generate appropriate tags for each output datatypes by adding / removing necessary tags and outputting to products.json. App should be able to read the config.json, find the input dataset and its tags, then modify the list of tags before outputing to products.json.

**Comment by soichih** [comment]
A road block on pushing apps to use product.json to reset the datatype_tags..

Currently, user can submit tasks on Brain-Life UI before previous task has completed. We can do this because we know the output datatypes and datatype_tags are assumed to be static; we can find apps that user *should be able to* submit next based on the expected output datatype and tags of the previous task.

Now, if we allow apps to dynamically change the datatype tags via product.json then we won't know exactly what datatype tags will be set until the previous task finishes. 

I don't know how to solve this at the moment..

**Comment by soichih** [comment]
I've had a few more months to think about this, and now I believe that output datatype_tags should be deterministic, which allows UI to construct a workflow before all dependent tasks has been completed.

So, to deal with following use-case ...

> 2. Another app like app-tractclassification may want to set different datatype tags based on the configuration option used (like "remove_fiber_before" or "remove_fiber_after").

What we should do in this case is to register 2 different apps on Brainlife - one with remove_fiber set to "before" and another one with "after" both pointing to the same github repo. (We recently made updates to allow readonly configuration parameter, and application description can be overridden). Then each app can be configured to output different datatype tags. 

However, I still believe we can, and should allow application to *add* datatypes tags to the datatype tags of the input dataset - instead of completely overriding it each time. To *add* a datatype, we need which input dataset that the tags should be copied from. For this, I believe we could introduce a new field under output dataset definition called `datatype_tags_from` and let user specify the input from a dropdown. UI and new process dialog can then concatenate all tags specified by `datatype_tags_from` and its own datatype_tags. 

I somehow believe that datatype tags should never be removed (because we always use tags to describe subset of dataset type - so once output is created to be a subset of something, it should not generalize back; I need a mathematician to help me with this idea)

**Comment by soichih** [comment]
datatype itself can not be modified, but datatype_tags can be set by product.json
