### ISSUE TITLE
Process update events are not received or handled by processes page

### ISSUE THREAD

**Issue by soichih** [brainlife/warehouse#92]
When an instance status is updated, that event doesn't seem to propagate to the processes UI.

**Comment by soichih** [comment]
Franco noticed this issue also. @stevengeeky Would you like to work on this issue next?

**Comment by stevengeeky** [comment]
@soichih currently still revising tractviewer, but I can work on this as well

**Comment by soichih** [comment]
Another odd thing that I just noticed.. It looks like I am receiving task events from processes other than the one that I am currently viewing. I wonder if there is a flaw in how destroyed() hook is handling un-subscription (or this could be a server side issue)

**Comment by soichih** [comment]
It looks like the stop events are properly propagated, but not start.

**Comment by soichih** [comment]
I've made a few more updates that might be related to this issue. Please let me know if this is still an issue.
