### ISSUE TITLE
Wish (download and upload a series of process steps from the brain-life process page)

### ISSUE THREAD

**Issue by francopestilli** [brainlife/warehouse#98]
Imagine a perfect world, where I could set up an analysis stream by running a series of apps in a data set and then after making sure that results look good I could "save" or "download" a file with the full pipeline. That file could in this ideal world be then loaded or uploaded by a different user and the user would be allowed to re-use the pipeline on a new data set.

**Comment by soichih** [comment]
I believe `provenance.sh` can more of less accomplish this.
