### ISSUE TITLE
Wish DOI of paper for each App

### ISSUE THREAD

**Issue by francopestilli** [brainlife/warehouse#99]
Imagine a world where each App has a primary DOI field where the App developer can add the DOi to the paper her/him published implementing the method. This DOI will then compile into a citation inside the warehouse. Additional DOi could be also added into a filed of "additional citations."

**Comment by soichih** [comment]
I've asked Datacite to allow me to experiment with their DOI registration API. If it works, we should become a member and implementing what you have described shouldn't be too hard on our end.

**Comment by francopestilli** [comment]
Let's go for it.

**Comment by soichih** [comment]
Datacite gave me access to their test metadata API server. I've played with it a bit and having some issue with authentication. I am working with Datacite support to resolve this issue, but so far so good!

**Comment by soichih** [comment]
@francopestilli I think I was misunderstanding your original request, but we could do 1 or following, or both.

1) Allow users to register a list of citations (references?) on "app". Under publication / app tab, show apps and list of all citations from each app.

2) When a user registers a new app, mint a new DOI from Datacite (similar to how publication records gets a new DOI). Under publication / app tab, show apps and list the app's DOI.

I think .. we should do 1) to allow entering references for each app, but for citation *to* the app we can also do 2) to generate the DOI and let user point to the brain-life's app (public) page. What do you think?

**Comment by soichih** [comment]
I've implemented a capability to issue new DOI for all registered App. 

Now, not all App would probably want to use Brainlife issued DOI - they might want to reference other DOI instead.. but that's a TODO for another time. 

My next goal is to enumerate all Apps used to generate published datasets under publication, and we can also list DOIs for each Apps (that points back to Brainlife).
